---
# Implement your Pre Workload deployment tasks here

- name: Create user Quota - clusterresourcequota
  shell: |
        oc create clusterquota clusterquota-"{{ ocp_username }}-{{ guid }}" \
        --project-annotation-selector=openshift.io/requester="{{ ocp_username }}" \
        --hard requests.cpu="{{ quota_requests_cpu }}" \
        --hard limits.cpu="{{ quota_limits_cpu }}"  \
        --hard requests.memory="{{ quota_requests_memory }}" \
        --hard limits.memory="{{ quota_limits_memory }}" \
        --hard configmaps="{{ quota_configmaps }}" \
        --hard pods="{{ quota_pods }}" \
        --hard persistentvolumeclaims="{{ quota_persistentvolumeclaims }}"  \
        --hard services="{{ quota_services }}" \
        --hard secrets="{{ quota_secrets }}" \
        --hard requests.storage="{{ quota_requests_storage }}"
  ignore_errors: true

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."