---

- name: "delete Kogito operator role for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-operator-role.yml' ) | from_yaml }}"

- name: "delete Kogito service-viewer role for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-service-viewer-role.yml' ) | from_yaml }}"

- name: "delete Kogito operator service account for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-operator-serviceaccount.yml' ) | from_yaml }}"

- name: "delete Kogito service-viewer service account for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-service-viewer-serviceaccount.yml' ) | from_yaml }}"

- name: "delete Kogito operator rolebinding for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-operator-rolebinding.yml' ) | from_yaml }}"

- name: "delete Kogito service-viewer rolebinding for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-service-viewer-rolebinding.yml' ) | from_yaml }}"
