---

- name: "create Kogito operator service account for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-operator-serviceaccount.yml' ) | from_yaml }}"

- name: "create Kogito service-viewer service account for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-service-viewer-serviceaccount.yml' ) | from_yaml }}"

- name: "create Kogito operator role for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-operator-role.yml' ) | from_yaml }}"

- name: "create Kogito service-viewer role for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-service-viewer-role.yml' ) | from_yaml }}"

- name: "create Kogito operator rolebinding for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-operator-rolebinding.yml' ) | from_yaml }}"

- name: "create Kogito service-viewer rolebinding for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-service-viewer-rolebinding.yml' ) | from_yaml }}"

- name: "create Kogito operator deployment for user user{{ user_num }}"
  k8s:
    state: present
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/kogito/operator/kogito-operator-deployment.yml' ) | from_yaml }}"
